[package]
name = "tamp-sys"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Bindings to the tamp compression C library"

[features]
default = ["compressor", "decompressor"]
compressor = []
decompressor = []

[build-dependencies]
bindgen = "0.72"
cc = "1.0"
